const names = {
    AUTH_REQUEST: 'LOGIN',
    GOOGLE_AUTH_REQUEST: 'LOGIN_GOOGLE',
    AUTH_LOGOUT: 'LOGOUT',
    AUTH_SUCCESS: 'LOGIN_SUCCESSFUL',
    GOOGLE_AUTH_SUCCESS: 'GOOGLE_LOGIN_SUCCESSFUL',
    AUTH_ERROR: 'LOGIN_UNSUCCESSFUL',
}

export default names